---
title: "Project"
author: "Group5"
date: '2022-03-22'
output: pdf_document
---

GitHub Link:

# Load Package
```{r}

library(tidyr)
library(MASS)
library(MuMIn)
library(ggplot2)
library(reshape2)
library(grid)
library(gridExtra)
library(ggfortify)
library(dplyr)

```

# Import Data
```{r}
###NK & HB lifetime reproductive success data
ltrsHB <- read.csv("./Data/HargreavesEcolLett data ltrsHB.csv")
ltrsNK <- read.csv("./Data/HargreavesEcolLett data ltrsNK.csv")

###NK & HB phenology data
phenNK <- read.csv("./Data/HargreavesEcolLett data phenologyNK.csv")
phenHB <- read.csv("./Data/HargreavesEcolLett data phenologyHB.csv")
```

```{r}
str(phenHB)
```


# Combine Datasets and Subset 
```{r}

# Merging HB and NK phenology datasets

phenmerged <- rbind(phenNK, phenHB)

# Subset phendat to variable we want

phendat <- phenmerged %>% dplyr::select(peak = transect, year, source = Source, site, treatment = treat, 
                                        final_fate = final.fate, DEm_plotavg = DEm.estplotav)



```




## PCA
```{r}
# delete rows with NA value
USBwithF1NA <- USBwithF1 %>%
    na.omit
names(USBwithF1NA)
```


Do plants transplanted from low-, mid-, and high- ranges vary in their ability to phenologically adapt to ranges outside their native range? (Fig. 2)
```{r}

```

